version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=maxwell
    ports:
      - 3306:3306
    volumes:
      - ./mysql-conf.d:/etc/mysql/conf.d

  maxwell:
    image: gcr.io/ditto-1470749749381/maxwell:9606af516f74092186eb0f3a842f92c209075b38
    command: bin/maxwell
    volumes:
      - ./maxwell/config.properties:/app/config.properties
    depends_on:
      - mysql
      - redis
    restart: always

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
